// Generated by gencpp from file rl_navigation/pause.msg
// DO NOT EDIT!


#ifndef RL_NAVIGATION_MESSAGE_PAUSE_H
#define RL_NAVIGATION_MESSAGE_PAUSE_H

#include <ros/service_traits.h>


#include <rl_navigation/pauseRequest.h>
#include <rl_navigation/pauseResponse.h>


namespace rl_navigation
{

struct pause
{

typedef pauseRequest Request;
typedef pauseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pause
} // namespace rl_navigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rl_navigation::pause > {
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::rl_navigation::pause&) { return value(); }
};

template<>
struct DataType< ::rl_navigation::pause > {
  static const char* value()
  {
    return "rl_navigation/pause";
  }

  static const char* value(const ::rl_navigation::pause&) { return value(); }
};


// service_traits::MD5Sum< ::rl_navigation::pauseRequest> should match
// service_traits::MD5Sum< ::rl_navigation::pause >
template<>
struct MD5Sum< ::rl_navigation::pauseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rl_navigation::pause >::value();
  }
  static const char* value(const ::rl_navigation::pauseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rl_navigation::pauseRequest> should match
// service_traits::DataType< ::rl_navigation::pause >
template<>
struct DataType< ::rl_navigation::pauseRequest>
{
  static const char* value()
  {
    return DataType< ::rl_navigation::pause >::value();
  }
  static const char* value(const ::rl_navigation::pauseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rl_navigation::pauseResponse> should match
// service_traits::MD5Sum< ::rl_navigation::pause >
template<>
struct MD5Sum< ::rl_navigation::pauseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rl_navigation::pause >::value();
  }
  static const char* value(const ::rl_navigation::pauseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rl_navigation::pauseResponse> should match
// service_traits::DataType< ::rl_navigation::pause >
template<>
struct DataType< ::rl_navigation::pauseResponse>
{
  static const char* value()
  {
    return DataType< ::rl_navigation::pause >::value();
  }
  static const char* value(const ::rl_navigation::pauseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RL_NAVIGATION_MESSAGE_PAUSE_H
