// Generated by gencpp from file rl_navigation/start.msg
// DO NOT EDIT!


#ifndef RL_NAVIGATION_MESSAGE_START_H
#define RL_NAVIGATION_MESSAGE_START_H

#include <ros/service_traits.h>


#include <rl_navigation/startRequest.h>
#include <rl_navigation/startResponse.h>


namespace rl_navigation
{

struct start
{

typedef startRequest Request;
typedef startResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct start
} // namespace rl_navigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rl_navigation::start > {
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::rl_navigation::start&) { return value(); }
};

template<>
struct DataType< ::rl_navigation::start > {
  static const char* value()
  {
    return "rl_navigation/start";
  }

  static const char* value(const ::rl_navigation::start&) { return value(); }
};


// service_traits::MD5Sum< ::rl_navigation::startRequest> should match
// service_traits::MD5Sum< ::rl_navigation::start >
template<>
struct MD5Sum< ::rl_navigation::startRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rl_navigation::start >::value();
  }
  static const char* value(const ::rl_navigation::startRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rl_navigation::startRequest> should match
// service_traits::DataType< ::rl_navigation::start >
template<>
struct DataType< ::rl_navigation::startRequest>
{
  static const char* value()
  {
    return DataType< ::rl_navigation::start >::value();
  }
  static const char* value(const ::rl_navigation::startRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rl_navigation::startResponse> should match
// service_traits::MD5Sum< ::rl_navigation::start >
template<>
struct MD5Sum< ::rl_navigation::startResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rl_navigation::start >::value();
  }
  static const char* value(const ::rl_navigation::startResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rl_navigation::startResponse> should match
// service_traits::DataType< ::rl_navigation::start >
template<>
struct DataType< ::rl_navigation::startResponse>
{
  static const char* value()
  {
    return DataType< ::rl_navigation::start >::value();
  }
  static const char* value(const ::rl_navigation::startResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RL_NAVIGATION_MESSAGE_START_H
