// Generated by gencpp from file rl_navigation/stop.msg
// DO NOT EDIT!


#ifndef RL_NAVIGATION_MESSAGE_STOP_H
#define RL_NAVIGATION_MESSAGE_STOP_H

#include <ros/service_traits.h>


#include <rl_navigation/stopRequest.h>
#include <rl_navigation/stopResponse.h>


namespace rl_navigation
{

struct stop
{

typedef stopRequest Request;
typedef stopResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct stop
} // namespace rl_navigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rl_navigation::stop > {
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::rl_navigation::stop&) { return value(); }
};

template<>
struct DataType< ::rl_navigation::stop > {
  static const char* value()
  {
    return "rl_navigation/stop";
  }

  static const char* value(const ::rl_navigation::stop&) { return value(); }
};


// service_traits::MD5Sum< ::rl_navigation::stopRequest> should match
// service_traits::MD5Sum< ::rl_navigation::stop >
template<>
struct MD5Sum< ::rl_navigation::stopRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rl_navigation::stop >::value();
  }
  static const char* value(const ::rl_navigation::stopRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rl_navigation::stopRequest> should match
// service_traits::DataType< ::rl_navigation::stop >
template<>
struct DataType< ::rl_navigation::stopRequest>
{
  static const char* value()
  {
    return DataType< ::rl_navigation::stop >::value();
  }
  static const char* value(const ::rl_navigation::stopRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rl_navigation::stopResponse> should match
// service_traits::MD5Sum< ::rl_navigation::stop >
template<>
struct MD5Sum< ::rl_navigation::stopResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rl_navigation::stop >::value();
  }
  static const char* value(const ::rl_navigation::stopResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rl_navigation::stopResponse> should match
// service_traits::DataType< ::rl_navigation::stop >
template<>
struct DataType< ::rl_navigation::stopResponse>
{
  static const char* value()
  {
    return DataType< ::rl_navigation::stop >::value();
  }
  static const char* value(const ::rl_navigation::stopResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RL_NAVIGATION_MESSAGE_STOP_H
