// Generated by gencpp from file duckiepond_vehicle/UsvDrive.msg
// DO NOT EDIT!


#ifndef DUCKIEPOND_VEHICLE_MESSAGE_USVDRIVE_H
#define DUCKIEPOND_VEHICLE_MESSAGE_USVDRIVE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace duckiepond_vehicle
{
template <class ContainerAllocator>
struct UsvDrive_
{
  typedef UsvDrive_<ContainerAllocator> Type;

  UsvDrive_()
    : header()
    , left(0.0)
    , right(0.0)  {
    }
  UsvDrive_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left(0.0)
    , right(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _left_type;
  _left_type left;

   typedef float _right_type;
  _right_type right;





  typedef boost::shared_ptr< ::duckiepond_vehicle::UsvDrive_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::duckiepond_vehicle::UsvDrive_<ContainerAllocator> const> ConstPtr;

}; // struct UsvDrive_

typedef ::duckiepond_vehicle::UsvDrive_<std::allocator<void> > UsvDrive;

typedef boost::shared_ptr< ::duckiepond_vehicle::UsvDrive > UsvDrivePtr;
typedef boost::shared_ptr< ::duckiepond_vehicle::UsvDrive const> UsvDriveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::duckiepond_vehicle::UsvDrive_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::duckiepond_vehicle::UsvDrive_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::duckiepond_vehicle::UsvDrive_<ContainerAllocator1> & lhs, const ::duckiepond_vehicle::UsvDrive_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.left == rhs.left &&
    lhs.right == rhs.right;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::duckiepond_vehicle::UsvDrive_<ContainerAllocator1> & lhs, const ::duckiepond_vehicle::UsvDrive_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace duckiepond_vehicle

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::duckiepond_vehicle::UsvDrive_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::duckiepond_vehicle::UsvDrive_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duckiepond_vehicle::UsvDrive_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duckiepond_vehicle::UsvDrive_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckiepond_vehicle::UsvDrive_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckiepond_vehicle::UsvDrive_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::duckiepond_vehicle::UsvDrive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b7824dbc6876539e023bc92130e483cb";
  }

  static const char* value(const ::duckiepond_vehicle::UsvDrive_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb7824dbc6876539eULL;
  static const uint64_t static_value2 = 0x023bc92130e483cbULL;
};

template<class ContainerAllocator>
struct DataType< ::duckiepond_vehicle::UsvDrive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "duckiepond_vehicle/UsvDrive";
  }

  static const char* value(const ::duckiepond_vehicle::UsvDrive_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::duckiepond_vehicle::UsvDrive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Standard USV thrust massage - port and starbard\n"
"\n"
"# Thrust command - typically ranges from {-1.0 - 1.0}\n"
"Header header\n"
"float32 left\n"
"float32 right\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::duckiepond_vehicle::UsvDrive_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::duckiepond_vehicle::UsvDrive_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left);
      stream.next(m.right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UsvDrive_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::duckiepond_vehicle::UsvDrive_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::duckiepond_vehicle::UsvDrive_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left: ";
    Printer<float>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<float>::stream(s, indent + "  ", v.right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUCKIEPOND_VEHICLE_MESSAGE_USVDRIVE_H
